import SenVang from "../img/cphsenvnghnhnhnxayphclong.png";
import OLong from "../img/olong.png";
import TrauLanh from "../img/traulanhnontom.png";
import TraLai from "../img/jasmine.png";
import DacCam from "../img/daccam.png";
import DacThom from "../img/trcclphuclong.png";
import OLongSua from "../img/trsolongphclong.png";
import TraDao from "../img/trophclong.png";

export const DEFAULT_PRODUCT = [
    {
      id: "1",
      badge: "Món mới",
      imgUrl: `${SenVang}`,
      name: "Cà Phê Sen Vàng HN Đá Xay",
      desc: "Almond Lotus Cappucino Crunch",
      price: 75000,
      btn: "ĐẶT HÀNG",
      quantity: 1,
    },
    {
      id: "2",
      badge: "Món mới",
      imgUrl: `${OLong}`,
      name: "Trà OLong Ủ Lạnh",
      desc: "Cold Brew Oolong Tea",
      price: 35000,
      btn: "ĐẶT HÀNG",
      quantity: 1,
    },
    {
      id: "3",
      badge: "Món mới",
      imgUrl: `${TrauLanh}`,
      name: "Trà Nõn Tôm Ủ Lạnh",
      desc: "Cold Brew Top Bud Green Tea",
      price: 35000,
      btn: "ĐẶT HÀNG",
      quantity: 1,
    },
    {
      id: "4",
      badge: "Món mới",
      imgUrl: `${TraLai}`,
      name: "Trà Lài Ủ Lạnh",
      desc: "Cold Brew Jasmine Tea",
      price: 28000,
      btn: "ĐẶT HÀNG",
      quantity: 1,
    },
    {
      id: "5",
      badge: "Món mới",
      imgUrl: `${DacCam}`,
      name: "Hồng Trà Đác Cam",
      desc: "Forest Black Tea",
      price: 65000,
      btn: "ĐẶT HÀNG",
      quantity: 1,
    },
    {
      id: "6",
      badge: "Món mới",
      imgUrl: `${DacThom}`,
      name: "Trà Lài Đác Thơm",
      desc: "Forest Jasmine Tea",
      price: 50000,
      btn: "ĐẶT HÀNG",
      quantity: 1,
    },
    {
      id: "7",
      badge: "Món mới",
      imgUrl: `${OLongSua}`,
      name: "Trà Ô Long sữa",
      desc: "Oolong Milk Tea",
      price: 45000,
      btn: "ĐẶT HÀNG",
      quantity: 1,
    },
    {
      id: "8",
      badge: "Món mới",
      imgUrl: `${TraDao}`,
      name: "Trà Đào",
      desc: "Peach Black Tea",
      price: 50000,
      btn: "ĐẶT HÀNG",
      quantity: 1,
    },
    {
      id: "9",
      badge: "Món mới",
      imgUrl: `${SenVang}`,
      name: "Cà Phê Sen Vàng HN Đá Xay",
      desc: "Almond Lotus Cappucino Crunch",
      price: 75000,
      btn: "ĐẶT HÀNG",
      quantity: 1,
    },
    {
      id: "10",
      badge: "Món mới",
      imgUrl: `${OLong}`,
      name: "Trà OLong Ủ Lạnh",
      desc: "Cold Brew Oolong Tea",
      price: 35000,
      btn: "ĐẶT HÀNG",
      quantity: 1,
    },
    {
      id: "11",
      badge: "Món mới",
      imgUrl: `${TrauLanh}`,
      name: "Trà Nõn Tôm Ủ Lạnh",
      desc: "Cold Brew Top Bud Green Tea",
      price: 35000,
      btn: "ĐẶT HÀNG",
      quantity: 1,
    },
    {
      id: "12",
      badge: "Món mới",
      imgUrl: `${TraLai}`,
      name: "Trà Lài Ủ Lạnh",
      desc: "Cold Brew Jasmine Tea",
      price: 28000,
      btn: "ĐẶT HÀNG",
      quantity: 1,
    },
    {
      id: "13",
      badge: "Món mới",
      imgUrl: `${DacCam}`,
      name: "Hồng Trà Đác Cam",
      desc: "Forest Black Tea",
      price: 65000,
      btn: "ĐẶT HÀNG",
      quantity: 1,
    },
    {
      id: "14",
      badge: "Món mới",
      imgUrl: `${DacThom}`,
      name: "Trà Lài Đác Thơm",
      desc: "Forest Jasmine Tea",
      price: 50000,
      btn: "ĐẶT HÀNG",
      quantity: 1,
    },
    {
      id: "15",
      badge: "Món mới",
      imgUrl: `${OLongSua}`,
      name: "Trà Ô Long sữa",
      desc: "Oolong Milk Tea",
      price: 45000,
      btn: "ĐẶT HÀNG",
      quantity: 1,
    },
    {
      id: "16",
      badge: "Món mới",
      imgUrl: `${TraDao}`,
      name: "Trà Đào",
      desc: "Peach Black Tea",
      price: 50000,
      btn: "ĐẶT HÀNG",
      quantity: 1,
    },
  ];

  